service: addressbook
image: tomfern/addressbook
servers:
  - 216.238.101.228
env:
  clear:
    # DB_USER: postgres
    # DB_SCHEMA: postgres
    DB_HOST: 216.238.113.141
    # DB_PORT: 5432
  secret:
    - DB_PASSWORD
registry:
  username: tomfern
  password:
    - DOCKER_PASSWORD

accessories:
  database:
    image: postgres:14
    host: 216.238.113.141
    port: 5432
    env:
      secret:
        - POSTGRES_PASSWORD
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data


# mrsk app exec --reuse "npm run migrate"
